name = "Serenity Heights"
author = "LostDoll"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8329cff053bb940f91ce860f1001d290786a1e6b9e91cb9e066a317bf622a416"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
