name = "Serenity Heights"
author = "LostDoll"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "385e5914f2300dbd69f081725a8df230771360040ed158c662ff37e99f872f94"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
