name = "Serenity Heights"
author = "LostDoll"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "59e71b99618d62be5d62ad37eee3801009bbed9529f6d15b4c4e3813a86d9204"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
